apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Dynatrace
    type: dynatrace
    access: proxy
    url: https://your-tenant.live.dynatrace.com
    jsonData:
      apiToken: ${DYNATRACE_API_TOKEN}
    editable: false
